name: dispanser-ml-notes
version: '0.0.1'
category: template
synopsis: Some implementations of various ML algorithms and concepts.
description: >
  personal playground for developing a better understanding of machine learning, including
  some implementations of basic algorithms.
author: Thomas Peiselt
github: dispanser/machine-learning-journey
license: MIT

ghc-options: -Wall
dependencies:
  - base >= 4.8.0 && <5
  - relude
  - split
  - vector
  - text
  - containers
  - unordered-containers
  - csv
  - formatting
  - scientific
  - pretty-simple
  - ghc-prim
  - microlens
  - statistics
  - mwc-random
  - mwc-probability
  - primitive
  - hmatrix
  - JuicyPixels
  - time

library:
  source-dirs: src
  dependencies:
    - random
    - hashable
    - Chart
    - binary
    - bytestring
    - either

executables:
  examples:
    source-dirs: examples
    main: ML/NeuralNetworks/MNIST.hs
    dependencies:
      - dispanser-ml-notes
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -optc-ffast-math
      - -fexcess-precision
      - -main-is ML.NeuralNetworks.MNIST

tests:
  tasty:
    source-dirs: tasty
    main: Discover.hs
    dependencies:
      - dispanser-ml-notes
      - hspec
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-quickcheck
      - tasty-hunit
      - tasty-hspec

benchmarks:
  benchmark-criterion:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
    dependencies:
      - dispanser-ml-notes
      - criterion
