name: isl
version: '0.0.0'
category: template
synopsis: Introduction to Statistical Learning, Haskell Edition
description: >
  aims to reproduce examples and exercises from 'Introduction to Statistical Learning' using Haskell
author: Thomas Peiselt
github: dispanser/isl-haskell
license: MIT

ghc-options: -Wall
dependencies:
  - base-noprelude >= 4.8.0 && <5
  - relude
  - vector
  - text
  - containers
  - unordered-containers
  - csv
  - formatting
  - scientific
  - pretty-simple
  - Frames
  - foldl
  - foldl-statistics
  - vinyl
  - ghc-prim
  - microlens
  - statistics

library:
  source-dirs: src
  dependencies:
    - random
    - hashable
    - microlens
    - Chart
    - hmatrix
    - hmatrix-morpheus

executables:
  examples:
    source-dirs: examples
    main: Kaggle/HousingExampleCompetition.hs
    dependencies:
      - isl
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Kaggle.HousingExampleCompetition

tests:
  tasty:
    source-dirs: tasty
    main: Discover.hs
    dependencies:
      - isl
      - hspec
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-quickcheck
      - tasty-hunit
      - tasty-hspec

benchmarks:
  benchmark-criterion:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
    dependencies:
      - isl
      - criterion
